codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "50...70"
  status:
    patch: off
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      default:
        target: auto
        threshold: 10%
        base: auto 
        if_ci_failed: success
        informational: true
        only_pulls: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no
  after_n_builds: 1